-- MySQL Script generated by MySQL Workbench
-- 07/11/15 18:21:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookdrift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookdrift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookdrift` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bookdrift` ;

-- -----------------------------------------------------
-- Table `bookdrift`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `address` LONGTEXT NOT NULL,
  `createTime` DATE NOT NULL,
  `avatar` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdrift`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `kind` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(100) NULL,
  `originOwner_id` INT(11) NOT NULL,
  `currentOwner_id` INT(11) NOT NULL,
  `createTime` DATE NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `own_idx` (`originOwner_id` ASC, `currentOwner_id` ASC),
  CONSTRAINT `own`
    FOREIGN KEY (`originOwner_id` , `currentOwner_id`)
    REFERENCES `bookdrift`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdrift`.`drift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`drift` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `isFinished` TINYINT(1) NOT NULL,
  `book_id` INT(11) NOT NULL,
  `lendTo_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lend_idx` (`book_id` ASC),
  INDEX `lend_idx1` (`lendTo_id` ASC),
  CONSTRAINT `drift`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookdrift`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lend`
    FOREIGN KEY (`lendTo_id`)
    REFERENCES `bookdrift`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdrift`.`driftApply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`driftApply` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `createTime` DATE NOT NULL,
  `book_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `request_idx` (`book_id` ASC),
  INDEX `request_idx1` (`user_id` ASC),
  CONSTRAINT `request`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookdrift`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `request`
    FOREIGN KEY (`user_id`)
    REFERENCES `bookdrift`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdrift`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`like` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `like_idx` (`user_id` ASC),
  INDEX `like_idx1` (`book_id` ASC),
  CONSTRAINT `like`
    FOREIGN KEY (`user_id`)
    REFERENCES `bookdrift`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `like`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookdrift`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdrift`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdrift`.`comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `mark` INT NULL,
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `publish_idx` (`user_id` ASC),
  INDEX `publish_idx1` (`book_id` ASC),
  CONSTRAINT `publish`
    FOREIGN KEY (`user_id`)
    REFERENCES `bookdrift`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publish`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookdrift`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
